name: Minikube

on:
  workflow_run:
    workflows: ["build-and-push-image"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Deploy to minikube
      run: |
        kubectl create -f kubernetes/daemonset.yaml
        kubectl wait pods -n kube-system -l name=barnowl --for condition=Ready --timeout=90s
        kubectl logs -n kube-system   -l name=barnowl do 
